// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: qr/v1/public/qr.proto

package public

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QRServiceClient is the client API for QRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QRServiceClient interface {
	RequestQR(ctx context.Context, in *RequestQRRequest, opts ...grpc.CallOption) (*RequestQRResponse, error)
}

type qRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQRServiceClient(cc grpc.ClientConnInterface) QRServiceClient {
	return &qRServiceClient{cc}
}

func (c *qRServiceClient) RequestQR(ctx context.Context, in *RequestQRRequest, opts ...grpc.CallOption) (*RequestQRResponse, error) {
	out := new(RequestQRResponse)
	err := c.cc.Invoke(ctx, "/public.QRService/RequestQR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QRServiceServer is the server API for QRService service.
// All implementations must embed UnimplementedQRServiceServer
// for forward compatibility
type QRServiceServer interface {
	RequestQR(context.Context, *RequestQRRequest) (*RequestQRResponse, error)
	mustEmbedUnimplementedQRServiceServer()
}

// UnimplementedQRServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQRServiceServer struct {
}

func (UnimplementedQRServiceServer) RequestQR(context.Context, *RequestQRRequest) (*RequestQRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestQR not implemented")
}
func (UnimplementedQRServiceServer) mustEmbedUnimplementedQRServiceServer() {}

// UnsafeQRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QRServiceServer will
// result in compilation errors.
type UnsafeQRServiceServer interface {
	mustEmbedUnimplementedQRServiceServer()
}

func RegisterQRServiceServer(s grpc.ServiceRegistrar, srv QRServiceServer) {
	s.RegisterService(&QRService_ServiceDesc, srv)
}

func _QRService_RequestQR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestQRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QRServiceServer).RequestQR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/public.QRService/RequestQR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QRServiceServer).RequestQR(ctx, req.(*RequestQRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QRService_ServiceDesc is the grpc.ServiceDesc for QRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "public.QRService",
	HandlerType: (*QRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestQR",
			Handler:    _QRService_RequestQR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qr/v1/public/qr.proto",
}
